// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StokTakipSistemi.Data;
using System;

namespace StokTakipSistemi.Migrations
{
    [DbContext(typeof(StokTakipSistemiDbContext))]
    [Migration("20181120154737_UserMigrations")]
    partial class UserMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StokTakipSistemi.Models.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdresText");

                    b.Property<int>("IlceId");

                    b.Property<int>("SehirId");

                    b.HasKey("Id");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Departman");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Tarih");

                    b.Property<int>("UrunSaglayiciId");

                    b.HasKey("Id");

                    b.ToTable("Fatura");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi");

                    b.Property<int>("AdresId");

                    b.HasKey("Id");

                    b.ToTable("Firma");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.Ilce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi");

                    b.Property<int>("SehirId");

                    b.HasKey("Id");

                    b.ToTable("Ilce");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi");

                    b.Property<DateTime>("Baslangic_Tarihi");

                    b.Property<int>("DepartmanId");

                    b.Property<DateTime>("Dogum_gunu");

                    b.Property<string>("Email");

                    b.Property<int>("FirmaId");

                    b.Property<string>("Sifre");

                    b.Property<string>("Soyadi");

                    b.Property<int>("UnvanId");

                    b.HasKey("Id");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.Marka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi");

                    b.HasKey("Id");

                    b.ToTable("Marka");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.Sehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi");

                    b.HasKey("Id");

                    b.ToTable("Sehir");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Adet");

                    b.Property<int>("FaturaId");

                    b.Property<int>("UrunId");

                    b.HasKey("Id");

                    b.ToTable("Siparis");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.Unvan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi");

                    b.Property<byte>("Indirim");

                    b.HasKey("Id");

                    b.ToTable("Unvan");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Adet");

                    b.Property<string>("Adi");

                    b.Property<decimal>("Fiyat");

                    b.Property<int>("MarkaId");

                    b.Property<int>("UrunTurId");

                    b.HasKey("Id");

                    b.ToTable("Urun");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.UrunSaglayici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi");

                    b.HasKey("Id");

                    b.ToTable("UrunSaglayici");
                });

            modelBuilder.Entity("StokTakipSistemi.Models.UrunTur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adi");

                    b.HasKey("Id");

                    b.ToTable("UrunTur");
                });
#pragma warning restore 612, 618
        }
    }
}
